version: "3.9"
services:
  # База даних PostgreSQL
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test_db
    volumes:
      - ./db/structure.sql:/docker-entrypoint-initdb.d/structure.sql
    ports:
      - "5432:5432"

  # Інтерфейс для перегляду бази (PgAdmin)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  # Ваш Python додаток (Store API)
  store:
    build: .
    container_name: store
    depends_on:
      - postgres_db
    environment:
      POSTGRES_HOST: postgres_db
      POSTGRES_USER: user
      POSTGRES_PASS: pass
      POSTGRES_DB: test_db
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
